backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

media_folder: "admin/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blurb" # Used in routes, e.g., /admin/collections/blog
    label: "Blurb" # Used in the UI
    folder: "admin/posts/blurb" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blurb"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}